module.exports = {
    gamemodes: {
        "Free for All": 0,
        "Team Deathmatch": 1,
        "Hardpoint": 2,
        "Capture the Flag": 3,
        "Parkour": 4,
        "Hide and Seek": 5,
        "Infected": 6,
        "Race": 7,
        "Last Man Standing": 8,
        "Simon Says": 9,
        "Gun Game": 10,
        "Prop Hunt": 11,
        "Boss Hunt": 12,
        "Classic FFA": 13,
        "Deposit": 14,
        "Stalker": 15,
        "King of the Hill": 16,
        "One in the Chamber": 17,
        "Trade": 18,
        "Kill Confirmed": 19,
        "Defuse": 20,
        "Sharp Shooter": 21,
        "Traitor": 22,
        "Raid": 23,
        "Blitz": 24,
        "Domination": 25,
        "Squad Deathmatch": 26,
        "Kranked FFA": 27,
        "Team Defender": 28,
        "Deposit FFA": 29,
        "Chaos Snipers": 33,
        "Bighead FFA": 34
    },
    maps: [
        "Burg", "Littletown", "Sandstorm", "Subzero", "Undergrowth",
        "Shipment", "Freight", "Lostworld", "Citadel", "Oasis",
        "Kanji", "Industry", "Lumber", "Evacuation", "Site",
        "SkyTemple", "Lagoon", "Bureau", "Tortuga", "Tropicano",
        "Krunk_Plaza", "Arena", "Habitat", "Atomic", "Old_Burg",
        "Throwback", "Stockade", "Facility"
    ],
    regions: {
        "Default": 0,
        "Frankfurt": "de-fra",
        "Silicon Valley": "us-ca-sv",
        "Sydney": "au-syd",
        "Tokyo": "jb-hnd",
        "Singapore": "sgp",
        "New York": "us-nj",
        "Mumbai": "as-mb",
        "Dallas": "us-tx",
        "Brazil": "brz",
        "Middle East": "me-bhn"
    }
};
